travis:
  secure:
    BINSTAR_TOKEN: nLcAr6aVdpOqevprZir6rttrpUbQZbzxB94bkEEHm5RQIFq5GpfzyaeU7I5UZglyQ0cp8phUCEccIV9Tlq7eMWz4YosR/jLRQijHCR9pQm8hz6tjPZTM9gSkD9QCXpKUoYUDS7wofD393Oql4STAj2Z4shoKGi40nJ5LzCy/VRa4nwcNhYIQBiTVzEWMfXNXa/Iq9Mu2MWZCDGt5Bh3aeZKksaUGKO2Jt0iIm6HF3nX6lVfOrVtubekr6YKRTq91kAIgiflurculkqvJfVvScS2C9U5WRfw1nW+hk1CSFurH8W4XoxlllMbZyjIawFZ6A7/tpXMi/KwtqwuIA64ZTUN2jn6lIuhNvXkk3ZQI2eZB7mX1CiPXkXGnTwdC1tP49+E8CKatVJfZj7Ms5UD5lDmw0YU9/C7EA+Q9/wjWPS9y6Vah8RSzln84/teBJj96sFug+izL/oqbeHbmHSszajT373Q15NkYotKxq3yRsk88h053NF0+oaUgCA0tyjz/8MsDvhu6+bGUJvz7Sngkyxoiz12wW+0QSE9/qoAMUscyB+/gVr5YR471LTfc31HLgw6p5UnlScRD5rY/XLVj5OcUoxQDhznJSGdNI++AYOJtRBN0oRyy6zhdD3IbSFFXXGbsJdNLJjjwaELqMHSmGHT8e3R4PMbzmwqs4ZO4okE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
